### PR TITLE
Renamed Metadata Entry Value size 

### PR DESCRIPTION
**Pull request by fboucquez**
To avoid generation conflicts in metadata_entry_types.cats (the size of the builder vs the size of the data)
It's also inline with the metadata transactions' value size field

### CODE REVIEW

**Comment by Jaguar0625** [comment]
Can you elaborate on what conflicts you're running into? Shouldn't size be scoped to struct?

**Comment by fboucquez** [comment]
Size also represents the size of the whole serialized stream. In metadata, we would have 2 sizes, the `size` of the data and the `size` of the builder (data size + 2). 

If we do this change:
1) the `valueSize` would be the same name as the transaction.  https://github.com/nemtech/catbuffer/blob/main/schemas/metadata/namespace_metadata.cats#L19
2) I don't need to revisit all the generators to avoid conflicts. I tried changing the generators to allow size as size field but it doesn't work out of the box.

This small change would do the code easier to understand (It took me some time to figure out there were 2 sizes, I'm guessing people with less experience will have the same problem), consistent in terms of naming, easier to write the generators.

**Comment by gimer** [comment]
Can you give example of generated code? or example where name clash is visible
somewhat more importantly... size field in model should *not* be accessible from the outside... (i.e. they should be only changed set via builders...)

**Comment by fboucquez** [comment]
Hi @gimer , 

Currently, the generators conflict with the "size" field name. There is a size but it's related to the whole size of the generated byte array/buffer, not to the individual field. If we rename `size` to `valueSize`  everything just works;

In TS:

With the proposed `valueSize` field:
```

export class MetadataValueBuilder {
    /** Data of the value. */
    data: Uint8Array;


    public constructor(data: Uint8Array) {
        this.data = data;
    }


    public static loadFromBinary(payload: Uint8Array): MetadataValueBuilder {
        const byteArray = Array.from(payload);
        const valueSize = GeneratorUtils.bufferToUint(GeneratorUtils.getBytes(Uint8Array.from(byteArray), 2));
        byteArray.splice(0, 2);
        const data = GeneratorUtils.getBytes(Uint8Array.from(byteArray), valueSize);
        byteArray.splice(0, valueSize);
        return new MetadataValueBuilder(data);
    }


    public getData(): Uint8Array {
        return this.data;
    }


    public getSize(): number {
        let size = 0;
        size += 2; // valueSize
        size += this.data.length;
        return size;
    }


    public serialize(): Uint8Array {
        let newArray = Uint8Array.from([]);
        const valueSizeBytes = GeneratorUtils.uintToBuffer(this.data.length, 2);
        newArray = GeneratorUtils.concatTypedArrays(newArray, valueSizeBytes);
        newArray = GeneratorUtils.concatTypedArrays(newArray, this.data);
        return newArray;
    }
}

```


With current `size` field:

```
/** Binary layout of a metadata entry value. */
export class MetadataValueBuilder {
    /** Size of the value. */
    size = 0;
    /** Data of the value. */
    data: Uint8Array;


    public constructor(data: Uint8Array) {
        this.data = data;
    }
    public static loadFromBinary(payload: Uint8Array): MetadataValueBuilder {
        const byteArray = Array.from(payload);
        const size = GeneratorUtils.bufferToUint(GeneratorUtils.getBytes(Uint8Array.from(byteArray), 2));
        byteArray.splice(0, 2);
        const data = GeneratorUtils.getBytes(Uint8Array.from(byteArray), size);
        byteArray.splice(0, size);
        return new MetadataValueBuilder(data);
    }

    public getData(): Uint8Array {
        return this.data;
    }
    public getSize(): number {
        let size = 0;
        size += 2; // size
        size += this.data.length;
        return size;
    } 
    public serialize(): Uint8Array {
        let newArray = Uint8Array.from([]);
        const sizeBytes = GeneratorUtils.uintToBuffer(this.getSize(), 2);
        newArray = GeneratorUtils.concatTypedArrays(newArray, sizeBytes);
        newArray = GeneratorUtils.concatTypedArrays(newArray, this.data);
        return newArray;
    }
}
```
A similar situation happens with Java, I guess python 2. 

I could spend time now trying to improve the generator or we can rename the field, be consistent with the transaction valueSize field name, and have the generation working.

**Comment by Jaguar0625** [comment]
Isn't the conflict simply because the generator is using a non-prefixed local variable named size? 
```
let size = 0;
```

**Comment by fboucquez** [comment]
Ok, I've fixed at generation. Thanks!

**Pull request closed without merging**
