### PR TITLE
Fixed resolutionEntry bug

### LINKED ISSUE #27: ResolutionEntry schema bug
`Resvoled` should be placed before `Source` in `ResolutionEntry` schema.

** This is affecting the serialization as the order is different from catapult-server serliaizer

### PR DESCRIPTION
**Pull request by rg911**
Fixed #27

### CODE REVIEW

**Comment by rg911** [comment]
@Jaguar0625 @gimer Sorry I missed this one.

**Comment by Jaguar0625** [comment]
can you explain what's wrong? the original version looks correct.

**Comment by rg911** [comment]
> can you explain what's wrong? the original version looks correct.

Hmm. Looks interesting now. on Catapult-server the previous one was right (source before resolved). But when generating the statement hash, the `Resolved` bytes need to be before the `ReceiptSource` otherwise I won't get the receipt merkle proof. Could that be the catapult-rest issue?

**Comment by BloodyRookie** [comment]
> the Resolved bytes need to be before the ReceiptSource otherwise I won't get the receipt merkle proof

Not sure i follow...

**Comment by rg911** [comment]
When serialize the `ResolutionEntry` to buffer, The generated builder follows the order defined in thecatbuffer schema.  Putting `ReceiptSource` before (in front of) `Resolved` will result in a different hash (different resolution entry bytes) generated which invalids the receipt merkle proof. Hope this makes sense

**Comment by BloodyRookie** [comment]
But the correct order (first ReceiptSource, then Resolved) is as it was before. Where is a different order used? In REST?

**Comment by rg911** [comment]
> But the correct order (first ReceiptSource, then Resolved) is as it was before. Where is a different order used? In REST?

Yeah. That confused me actually. This was picked up by running the e2e test against block receipts endpoint on rest. I can only get the receipt hash proofed by putting the resolved before source

**Comment by BloodyRookie** [comment]
Then it must be fixed on REST side but not in catbuffer

**Comment by Vektrat** [comment]
REST should return the same order it fetches from mongodb, though in some cases it may be altered (new fields, or similar situations)

either way REST order should **not** be trusted, this is why we have catbuffer at server and client side anyway, does not the client pick REST data, and serializes it following catbuffer schemas? i don't think REST requires fixing (again, most likely following mongodb order), rather the clients should serialize following catbuffer rules

**Comment by rg911** [comment]
> REST should return the same order it fetches from mongodb, though in some cases it may be altered (new fields, or similar situations)
> 
> either way REST order should **not** be trusted, this is why we have catbuffer at server and client side anyway, does not the client pick REST data, and serializes it following catbuffer schemas? i don't think REST requires fixing (again, most likely following mongodb order), rather the clients should serialize following catbuffer rules

If Rest is NOT following the buffer schema order, then that will be the issue, as the hash will be completely different. 
BWT, thanks for

**Comment by rg911** [comment]
One more question sorry. 
Does the statement merkle hash tree gets built on the catapult-server or rest? It seems to me the merkle tree was not built properly as it takes the wrong hash for proofing.

**Comment by Vektrat** [comment]
REST is not serializing anything, hashes are built at core, supposedly with catbuffer, and REST handles just already hashed data

for account state, REST fetches the audit path generated at core from the tree and returns it, for the other merkle trees (the ones that have been developed for a while, involving transaction and receipt merkle trees), REST builds the audit path from the tree of hashes it fetches from core - in both cases, hashes are generated at core, just in one of them, intermediate hashes (audit path) are generated at REST (no catbuffer required since they have nothing to do with object serialization)

**Pull request closed without merging**
